<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
      <UserSecretsId>328d1b7d-8a9d-4f26-8f1d-159161f33bcc</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="DotNetEnv" Version="3.1.1" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.0-preview.7.24405.7" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.0-preview.7.24405.7" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0-preview.7.24405.7" />
      <PackageReference Include="RestSharp" Version="112.0.0" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\.dockerignore">
          <Link>.dockerignore</Link>
        </Content>
        <Content Include="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
